name: Nob

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install xorg-dev
    - name: Bootstrap nob
      run: cc -o nob nob.c
    - name: Build with nob
      run: ./nob
